### ISSUE TITLE
[BUG] Issue growing Logical Volume 

### ISSUE THREAD

**Issue by jsliacan** [crc-org/crc#3718]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
CRC version: 2.21.0+e3efa9
OpenShift version: 4.13.0
Podman version: 4.4.4
```

## CRC config
```bash
- consent-telemetry                     : no
- preset                                : microshift
```

### Steps to reproduce

  1. install 2.21.0
  2. `crc setup`
  3. `crc start`
  4. 

### Logs
```
PS C:\Users\crcqe> crc setup
INFO Using bundle path C:\Users\crcqe\.crc\cache\crc_microshift_hyperv_4.13.0_amd64.crcbundle
INFO Checking minimum RAM requirements
INFO Checking if current user is in crc-users and Hyper-V admins group
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\crcqe\.crc\cache\crc_microshift_hyperv_4.13.0_amd64.crcbundle exists
INFO Checking if the daemon task is installed
INFO Installing the daemon task
INFO Checking if the daemon task is running
INFO Running the daemon task
INFO Checking admin helper service is running
Your system is correctly setup for using CRC. Use 'crc start' to start the instance
PS C:\Users\crcqe> crc start -p C:\Users\crcqe\Downloads\crc-pull-secret
INFO Checking minimum RAM requirements
INFO Checking if running in a shell with administrator rights
INFO Checking Windows release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if Hyper-V service is enabled
INFO Checking if crc-users group exists
INFO Checking if current user is in crc-users and Hyper-V admins group
INFO Checking if vsock is correctly configured
INFO Checking if the daemon task is installed
INFO Checking if the daemon task is running
INFO Checking admin helper service is running
INFO Loading bundle: crc_microshift_hyperv_4.13.0_amd64...
INFO Creating CRC VM for MicroShift 4.13.0...
INFO Generating new SSH key pair...
INFO Starting CRC VM for microshift 4.13.0...
INFO CRC instance is running with IP 127.0.0.1
INFO CRC VM is running
INFO Updating authorized keys...
panic: runtime error: slice bounds out of range [:8] with length 0

goroutine 1 [running]:
github.com/crc-org/crc/pkg/crc/machine.runGrowpart(0x0?, {0x0, 0x0})
        /builddir/build/BUILD/crc-2.21.0/pkg/crc/machine/start.go:161 +0x245
github.com/crc-org/crc/pkg/crc/machine.growLVForMicroshift(0x297ba6e?, {0x2983e92, 0x9})
        /builddir/build/BUILD/crc-2.21.0/pkg/crc/machine/start.go:180 +0x199
github.com/crc-org/crc/pkg/crc/machine.growRootFileSystem(0xc0000ce000?, {0x2986a35?, 0xc000a0f3a0?})
        /builddir/build/BUILD/crc-2.21.0/pkg/crc/machine/start.go:120 +0xc5
github.com/crc-org/crc/pkg/crc/machine.(*client).Start(0xc0002f0640, {0x2d1ee78, 0xc0002f1540}, {{0xc00055cdc0, 0x46}, 0x1000, 0x2, 0x1f, {0x0, 0x0}, ...})
        /builddir/build/BUILD/crc-2.21.0/pkg/crc/machine/start.go:439 +0x154b
github.com/crc-org/crc/pkg/crc/machine.(*Synchronized).Start(0xc0002f0680, {0x2d1ef20?, 0xc000636c60?}, {{0xc00055cdc0, 0x46}, 0x1000, 0x2, 0x1f, {0x0, 0x0}, ...})
        /builddir/build/BUILD/crc-2.21.0/pkg/crc/machine/sync.go:93 +0xca
github.com/crc-org/crc/cmd/crc/cmd.runStart({0x2d1ef20, 0xc000636c60})
        /builddir/build/BUILD/crc-2.21.0/cmd/crc/cmd/start.go:111 +0x5ad
github.com/crc-org/crc/cmd/crc/cmd.glob..func11(0x3d49520, {0x5?, 0x298c0dc?, 0xc?})
        /builddir/build/BUILD/crc-2.21.0/cmd/crc/cmd/start.go:57 +0x57
github.com/crc-org/crc/cmd/crc/cmd.executeWithLogging.func1(0x3d49520, {0xc00064c0e0, 0x0, 0x2})
        /builddir/build/BUILD/crc-2.21.0/cmd/crc/cmd/root.go:170 +0x102
github.com/spf13/cobra.(*Command).execute(0x3d49520, {0xc00064c0c0, 0x2, 0x2})
        /builddir/build/BUILD/crc-2.21.0/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x3d4af00)
        /builddir/build/BUILD/crc-2.21.0/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/crc-2.21.0/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/crc-2.21.0/vendor/github.com/spf13/cobra/command.go:961
github.com/crc-org/crc/cmd/crc/cmd.Execute()
        /builddir/build/BUILD/crc-2.21.0/cmd/crc/cmd/root.go:105 +0xd9
main.main()
        /builddir/build/BUILD/crc-2.21.0/cmd/crc/main.go:8 +0x17
```

**Comment by anjannath** [comment]
The panic seems to be coming from `github.com/crc-org/crc/pkg/crc/machine.runGrowpart(0x0?, {0x0, 0x0})`

**Comment by gbraad** [comment]
@anjannath next time, please update the title. This is related to growing/resizing the disk

**Comment by praveenkumar** [comment]
@jsliacan Can you share the debug logs of that run?

**Comment by jsliacan** [comment]
No, only what is in the issue. The `crc.json` file is as above and commands only those that you see there too. Very plain use.

**Comment by praveenkumar** [comment]
@jsliacan can you manually run and provide the debug logs?

**Comment by anjannath** [comment]
some relevant debug o/p from the VM:

```
[core@api ~]$ sudo lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda             8:0    0   49G  0 disk
├─sda1          8:1    0  800M  0 part /boot
├─sda2          8:2    0  200M  0 part /boot/efi
└─sda3          8:3    0   30G  0 part
  └─rhel-root 253:0    0   15G  0 lvm  /var/lib/containers/storage/overlay
                                       /var
                                       /sysroot/ostree/deploy/rhel/var
                                       /usr
                                       /etc
                                       /
                                       /sysroot
sr0            11:0    1 1024M  0 rom
````
---------

```
[core@api ~]$ sudo pvdisplay
  Devices file PVID BAUW2KTKhF3RE03h4JEMd1EImwC3cWd0 last seen on /dev/vda3 not found.
```

**Comment by anjannath** [comment]
changing the device names to `/dev/sda3` in the file  `/etc/lvm/devices/system.devices` seems to fix the issue now..
```
[core@api ~]$ cat /etc/lvm/devices/system.devices
# LVM uses devices listed in this file.
# Created by LVM command lvmdevices pid 2383 at Wed May 24 17:10:17 2023
VERSION=1.1.4
IDTYPE=devname IDNAME=/dev/sda3 DEVNAME=/dev/sda3 PVID=BAUW2KTKhF3RE03h4JEMd1EImwC3cWd0 PART=3
```

**Comment by praveenkumar** [comment]
After debugging with the @anjannath looks like what is happen
- We create our bundle on linux and there the partition and disk are named as `/dev/vda` and that is the configuration which lvm have
- when this bundle run on linux/mac `/dev/vda` is the device and it works without any issue.
- when this bundle run on windows the device changed to `/dev/sda` and all the `lv/pv/vg` commands start failing because the config still have IDNAME and DEVNAME ans `/dev/vda3` 
- So when we manually changed the `/etc/lvm/devices/system.devices` all the commands starts working.

**Comment by jsliacan** [comment]
> @jsliacan can you manually run and provide the debug logs?

Not sure this is still relevant, but here are the logs: https://gist.github.com/jsliacan/80285ec1b18c838bd032947e324d5521
