### ISSUE TITLE
Error for Hyper-V available check when management tools not installed

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3764]
The line:
https://github.com/crc-org/crc/blob/e43de8dfca711be4f76acef3d07b67ea121cbe1f/pkg/drivers/hyperv/powershell_windows.go#L47

will fail when Management tools aren't installed:

```
INFO Creating CRC VM for OpenShift 4.13.3...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/crc-org/crc/pkg/drivers/hyperv.hypervAvailable()
        /builddir/build/BUILD/crc-2.23.0/pkg/drivers/hyperv/powershell_windows.go:47 +0xb4
github.com/crc-org/crc/pkg/drivers/hyperv.(*Driver).PreCreateCheck(0xc0005edef0)
        /builddir/build/BUILD/crc-2.23.0/pkg/drivers/hyperv/hyperv_windows.go:119 +0x3c
github.com/crc-org/crc/pkg/crc/machine.createHost({{0xc000bb0d9a, 0x17}, {0x2320065, 0x3}, 0x2400, 0x4, 0x1f, {0xc0004f4940, 0x3a}, {0xc000dc1398, ...}, ...}, ...)
        /builddir/build/BUILD/crc-2.23.0/pkg/crc/machine/start.go:723 +0x19c
github.com/crc-org/crc/pkg/crc/machine.(*client).Start(0xc000daa5c0, {0x26cc6d8, 0xc000daad40}, {{0xc000bb0d80, 0x3b}, 0x2400, 0x4, 0x1f, {0x0, 0x0}, ...})
        /builddir/build/BUILD/crc-2.23.0/pkg/crc/machine/start.go:329 +0x9d8
github.com/crc-org/crc/pkg/crc/machine.(*Synchronized).Start(0xc000daa600, {0x26cc780?, 0xc000c805a0?}, {{0xc000bb0d80, 0x3b}, 0x2400, 0x4, 0x1f, {0x0, 0x0}, ...})
        /builddir/build/BUILD/crc-2.23.0/pkg/crc/machine/sync.go:93 +0xca
github.com/crc-org/crc/cmd/crc/cmd.runStart({0x26cc780, 0xc000c805a0})
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/start.go:111 +0x5ad
github.com/crc-org/crc/cmd/crc/cmd.glob..func11(0x3751c20, {0x5?, 0x2336a0c?, 0xc?})
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/start.go:57 +0x57
github.com/crc-org/crc/cmd/crc/cmd.executeWithLogging.func1(0x3751c20, {0x3cfc9f0, 0x0, 0x0})
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/root.go:170 +0x102
github.com/spf13/cobra.(*Command).execute(0x3751c20, {0x3cfc9f0, 0x0, 0x0})
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x3753600)
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/crc-2.23.0/vendor/github.com/spf13/cobra/command.go:961
github.com/crc-org/crc/cmd/crc/cmd.Execute()
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/cmd/root.go:105 +0xd9
main.main()
        /builddir/build/BUILD/crc-2.23.0/cmd/crc/main.go:8 +0x17
```

**Comment by adrianriobo** [comment]
not related maybe related #2555

**Comment by cfergeau** [comment]
This `resp[0]` pattern appears multiple times over this file. Since we only look at `resp[0]`, maybe `parseLines` should return a string instead of an array whose length we need to check.

**Comment by gbraad** [comment]
If there is no response, we have to fail... but perhaps be even more specific in the check.

**Comment by gbraad** [comment]
and yes, @adrianriobo this might be related. we have to make sure how this interacts. the report I saw spoke that the setup succeeded, but start would fail. It should always fail on setup (checks) first.

**Comment by cfergeau** [comment]
> will fail when Management tools aren't installed:

Looking at `hypervAvailable`, it is:
```

func hypervAvailable() error {
	stdout, err := cmdOut("@(Get-Module -ListAvailable hyper-v).Name | Get-Unique")
	if err != nil {
		return err
	}

	resp := parseLines(stdout)
	if resp[0] != "Hyper-V" {
		return ErrNotInstalled
	}

	return nil
}
```
If the tools aren't available, why isn't `cmdOut` returning an error?

**Comment by gbraad** [comment]
> why isn't `cmdOut` returning an error?

IIRC, this can not return an error as this is executed as a different user. In tht case you can only get the value, but not the error
