### ISSUE TITLE
[BUG] errors after increasing memory and cpu on M2 mac

### ISSUE THREAD

**Issue by oc-will-holtam** [crc-org/crc#3895]
### General information

  * OS: macOS
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it (Yes)
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.28.0+e1f42d
OpenShift version: 4.13.14
Podman version: 4.4.4
```
  
## CRC status
```bash
DEBU CRC version: 2.28.0+e1f42d
DEBU OpenShift version: 4.13.14
DEBU Podman version: 4.4.4
DEBU Running 'crc status'
CRC VM:          Stopped
OpenShift:       Stopped (v4.13.14)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     37.64GB
Cache Directory: /Users/will.holtam@gembaadvantage.com/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
```

### Steps to reproduce

  1. Install crc on M2 mac OS v14
  2. Change default configuration settings to increase memory and cpu (attempted values from cpus=8 and memory=15000 and lower)
  3. After multiple errors then attempt to go back to default configuration.
  4. Get error below

### Expected

CRC and OpenShift to be running with now issues. The ability to increase the memory and cpu allocated to 8 cpus and 15000 memory.

### Actual

Either I get a go panic error:
```
INFO 4 operators are progressing: image-registry, network, openshift-controller-manager, service-ca
DEBU panic: runtime/cgo: misuse of an invalid Handle
DEBU
DEBU goroutine 17 [running, locked to thread]:
DEBU runtime/cgo.Handle.Value(...)
DEBU 	/Users/runner/hostedtoolcache/go/1.20.5/x64/src/runtime/cgo/handle.go:124
DEBU github.com/Code-Hex/vz/v3.shouldAcceptNewConnectionHandler(0x14000032060?, 0x0?, 0x14000000001?)
DEBU 	/Users/runner/go/pkg/mod/github.com/!code-!hex/vz/v3@v3.0.6/socket.go:231 +0x11c
```

OR I get a timeout error:

```
ERRO Cluster is not ready: cluster operators are still not stable after 12m30.490641416s
INFO Adding crc-admin and crc-developer contexts to kubeconfig...
DEBU Using address: api.crc.testing:6443
DEBU Dialing to 127.0.0.1:6443
ERRO Cannot update kubeconfig: read tcp 127.0.0.1:53411->127.0.0.1:6443: read: connection reset by peer
Started the OpenShift Cluster.
```
After which when running crc status; CRC VM is RUNNING; but OpenShift is Unreachable.

OR I get:

```
fault   0x0
DEBU error: Temporary error: ssh command errror:
command : timeout 5s oc get secret --context admin --cluster crc --kubeconfig /opt/kubeconfig
err             : Process exited with status 2
 - sleeping 1s
Failed to update kubeadmin user password: Temporary error: ssh command error:
command : timeout 5s oc get secret --context admin --cluster crc --kubeconfig /opt/kubeconfig
err             : Process exited with status 127

DEBU error: Temporary error: ssh command errror:
command : timeout 5s oc get secret --context admin --cluster crc --kubeconfig /opt/kubeconfig
err             : Process exited with status 2
```

After this, the terminal hangs.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

This is the result of attempting the above commands:
https://gist.github.com/WilliamHoltam/a6a511f8caff4f6e309fc90c220104f9

**Comment by cfergeau** [comment]
```
DEBU panic: runtime/cgo: misuse of an invalid Handle
DEBU
DEBU goroutine 17 [running, locked to thread]:
DEBU runtime/cgo.Handle.Value(...)
DEBU 	/Users/runner/hostedtoolcache/go/1.20.5/x64/src/runtime/cgo/handle.go:124
DEBU github.com/Code-Hex/vz/v3.shouldAcceptNewConnectionHandler(0x14000032060?, 0x0?, 0x14000000001?)
DEBU 	/Users/runner/go/pkg/mod/github.com/!code-!hex/vz/v3@v3.0.6/socket.go:231 +0x11c
```

This is a vfkit bug which is  fixed by https://github.com/crc-org/vfkit/commit/17449d26252b59aca5f479c1245b815230dd89ae but I haven't made a release/added the fix to crc yet.

The other errors you are seeing could be related to a hard to reproduce bug in our network stack. You can try to kill all crc processes and try again.

**Comment by oc-will-holtam** [comment]
Thank you for your help @cfergeau.

I just attempted to kill all crc processes and try again, and this was the result:

```
DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s
DEBU retry loop: attempt 15
DEBU Running SSH command: <hidden>
DEBU SSH command failed
DEBU non-retriable error: failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : wait: remote command exited without exit status or exit signal
:
DEBU Error closing ssh client: close tcp 127.0.0.1:50777->127.0.0.1:2222: use of closed network connection
Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x15)
failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : wait: remote command exited without exit status or exit signal
```

Edit:
- I killed the crc process and made sure that vfkit was also stopped.
- I then ran `crc cleanup`; `crc setup`; `crc start --log-level debug`

**Comment by oc-will-holtam** [comment]
A subsequent attempt is also hitting what I think is the same vfkit bug you mentioned; but there was more output which might be useful.

https://gist.github.com/WilliamHoltam/fa71fcacc6f178c7075a92994405c057

**Comment by cfergeau** [comment]
First time I see this one, it seems to be happening in `oc` rather than in `vfkit` so I don't think it's the same.

**Comment by adrianriobo** [comment]
Just tested on an M2 with custom config and cluster is running, so I can not reproduce it:

```bash
ec2-user@Mac-mini ~ % crc status
CRC VM:          Running
OpenShift:       Running (v4.13.14)
RAM Usage:       6.797GB of 15.31GB
Disk Usage:      18.9GB of 32.68GB (Inside the CRC VM)
Cache Usage:     37.64GB
Cache Directory: /Users/ec2-user/.crc/cache
ec2-user@Mac-mini ~ % crc config view
- consent-telemetry                     : no
- cpus                                  : 8
- memory                                : 15000
ec2-user@Mac-mini ~ % sw_vers 
ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91
ec2-user@Mac-mini ~ % uname -a
Darwin Mac-mini.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
ec2-user@Mac-mini ~ % sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Apple M2 Pro
```

**Comment by oc-will-holtam** [comment]
Oh dear, well that's bad news for me I guess 😂 .

I attempted fully uninstalling crc by running `crc delete`, then deleting `/usr/local/bin/crc` and the crc cache location as well as killing all crc processes. I'm not 100% sure if I managed to get everything.

I then reinstalled crc and ran `crc setup` and `crc start` and ended up with a new error:

```
DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s
DEBU retry loop: attempt 14
DEBU Running SSH command: <hidden>
DEBU SSH command failed
DEBU non-retriable error: failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : Process exited with status 139 from signal SEGV
: /usr/libexec/grepconf.sh: line 3: 11777 Illegal instruction     (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 12054 Illegal instruction     (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 12373 Illegal instruction     (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x14)
failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : Process exited with status 139 from signal SEGV
: /usr/libexec/grepconf.sh: line 3: 11777 Illegal instruction     (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 12054 Illegal instruction     (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 12373 Illegal instruction     (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
```

**Comment by oc-will-holtam** [comment]
When I reinstall it says that it has to upgrade CRC; so I think I'm not doing a full uninstall. Do you have instructions for how to completely uninstall CRC on mac so that I can start clean? Thank you so much for your help @cfergeau @adrianriobo, it's much appreciated 👍

**Comment by adrianriobo** [comment]
Typically I would:

```bash
crc cleanup
rm -rf ~/.crc
```

That should be enough for cleanup everything

Is it possible after you cleaned up `2.28.0` you got some old binary which is being used...which is the output now for `crc version` ?

Also just in case I just tested on a M2 with sonoma and again it is running:

```bash
ec2-user@Mac-mini ~ % crc status
CRC VM:          Running
OpenShift:       Running (v4.13.14)
RAM Usage:       6.529GB of 9.353GB
Disk Usage:      19.2GB of 32.68GB (Inside the CRC VM)
Cache Usage:     37.64GB
Cache Directory: /Users/ec2-user/.crc/cache
ec2-user@Mac-mini ~ % sw_vers 
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
```

**Comment by oc-will-holtam** [comment]
CRC version: 2.28.0+e1f42d
OpenShift version: 4.13.14
Podman version: 4.4.4

**Comment by oc-will-holtam** [comment]
It decided so work for a day, but now I'm hitting the same bugs again. It's 1/5 chance whether or not it starts successfully on my machine; the behaviour isn't predictable

**Comment by gbraad** [comment]
I would suspect problems with the machine or OS itself. Not much we can do, as we can reproduce this on multiple machines.
