### ISSUE TITLE
[BUG] crc stuck on Linux machine

### ISSUE THREAD

**Issue by lilyLuLiu** [crc-org/crc#4342]
Machine: Red Hat Enterprise Linux release 8.10 (Ootpa)
The crc command stuck even for `crc version` or `crc help`. If reboot the machine, crc back to normal.
This happens frequently and only in this machine. 

>[cloud-user@rhel-crcqe ~]$ ps -elf | grep crc
0 S cloud-u+   97926       1  0  80   0 - 55650 -      Sep01 ?        00:00:00 /bin/bash crc-e2e/run.sh -targetFolder crc-e2e -junitFilename e2e-junit.xml -bundleLocation /home/cloud-user/OpenshiftLocal/bundle/4.16.7/crc_libvirt_4.16.7_amd64.crcbundle -e2eTagExpression ~@minimal && ~@story_microshift
0 S cloud-u+   97950   97926  0  80   0 - 527961 -     Sep01 ?        00:00:02 ./e2e.test --bundle-location=/home/cloud-user/OpenshiftLocal/bundle/4.16.7/crc_libvirt_4.16.7_amd64.crcbundle --pull-secret-file=/home/cloud-user/crc-e2e/pull-secret --cleanup-home=false --crc-memory= --godog.tags=linux && ~@minimal && ~@story_microshift --godog.format=junit
5 S dnsmasq   105622       1  0  80   0 - 14412 -      Sep01 ?        00:00:02 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/crc.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
1 S root      105623  105622  0  80   0 - 14405 -      Sep01 ?        00:00:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/crc.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
0 S cloud-u+  105950    1593  0  80   0 - 528058 -     Sep01 ?        00:00:07 /home/cloud-user/.crc/bin/crc daemon
6 S qemu      106370       1 71  80   0 - 4005494 -    Sep01 ?        19:49:04 /usr/libexec/qemu-kvm -name guest=crc,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-5-crc/master-key.aes"} -blockdev {"driver":"file","filename":"/usr/share/edk2/ovmf/OVMF_CODE.cc.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/crc_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-q35-rhel8.6.0,usb=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram -accel kvm -cpu host,migratable=on -m 10752 -object {"qom-type":"memory-backend-memfd","id":"pc.ram","share":true,"x-use-canonical-path-for-ramblock-id":false,"size":11274289152} -overcommit mem-lock=off -smp 4,sockets=4,cores=1,threads=1 -uuid 0186d168-bfe2-4fa7-a2c4-fb2565bfa5b4 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=35,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot menu=off,strict=on -device pcie-root-port,port=16,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 -device pcie-root-port,port=17,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 -device pcie-root-port,port=18,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 -device pcie-root-port,port=19,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 -device pcie-root-port,port=20,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 -device pcie-root-port,port=21,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5 -device qemu-xhci,id=usb,bus=pci.3,addr=0x0 -blockdev {"driver":"file","filename":"/home/cloud-user/.crc/cache/crc_libvirt_4.16.7_amd64/crc.qcow2","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":true,"driver":"qcow2","file":"libvirt-2-storage","backing":null} -blockdev {"driver":"file","filename":"/home/cloud-user/.crc/machines/crc/crc.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"} -device virtio-blk-pci,bus=pci.4,addr=0x0,drive=libvirt-1-format,id=virtio-disk0,bootindex=1 -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-5-crc/fs0-fs.sock -device vhost-user-fs-pci,id=fs0,chardev=chr-vu-fs0,tag=dir0,bus=pci.1,addr=0x0 -netdev tap,fd=36,id=hostnet0,vhost=on,vhostfd=38 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:fd:fc:07:21:82,bus=pci.2,addr=0x0 -chardev stdio,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -audiodev {"id":"audio1","driver":"none"} -vnc 127.0.0.1:0,audiodev=audio1 -device cirrus-vga,id=video0,bus=pcie.0,addr=0x1 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.5,addr=0x0 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
0 S cloud-u+  106704  106645  0  80   0 - 509433 -     Sep01 ?        00:00:02 crc podman-env
0 S cloud-u+  121100       1  0  80   0 - 55650 -      Sep01 ?        00:00:00 /bin/sh crc-support/run.sh main https://crcqe-asia.s3.amazonaws.com/nightly/microshift/4.16.7/20240901/RHEL-8.10 crc-linux-amd64.tar.xz.sha256sum /home/cloud-user/OpenshiftLocal/crc/main true true crc true false
0 S cloud-u+  121123  121100  0  80   0 - 546235 -     Sep01 ?        00:00:00 crc cleanup
0 S cloud-u+  124218       1  0  80   0 - 55650 -      02:38 ?        00:00:00 /bin/sh crc-support/run.sh main https://crcqe-asia.s3.amazonaws.com/nightly/crc/20240902/RHEL-8.10 crc-linux-amd64.tar.xz.sha256sum /home/cloud-user/OpenshiftLocal/crc/main true true crc true false
0 S cloud-u+  124241  124218  0  80   0 - 490872 -     02:38 ?        00:00:00 crc cleanup
0 S cloud-u+  128044  127877  0  80   0 - 55496 -      07:33 pts/0    00:00:00 grep --color=auto crc

**Comment by lilyLuLiu** [comment]
@anjannath made some investigation on the machine:
`crc` makes use of the secrets service of dbus on linux to store the pull-secret, but to unlock the secrets collection it needs a password, from a GUI you'll see a dialog asking you to enter the password, but while on a SSH session this is not possible so its stuck.

**Comment by praveenkumar** [comment]
@anjannath does this happen when `pull-secret-file` is used as part of config?

**Comment by anjannath** [comment]
> @anjannath does this happen when `pull-secret-file` is used as part of config?

this happens early on when we want to initialize the config object, so this happens even when `pull-secret-file` is set,  when executing this line: https://github.com/crc-org/crc/blob/4e80c4c48c6c0c13d0399cc0436a0a38d9dda0a2/cmd/crc/cmd/root.go#L152

this tries to determine if the secrets store is accessible by trying to store a value, but if the login secrets collection is locked, and `crc` is being run in an ssh session then it gets stuck, because the prompt to unlock the keyring is a GUI prompt

**Comment by albfan** [comment]
Agreed with @praveenkumar. Even if we want to triage and resolve this (crc stuck with accessing pull request) which probably is just timeout and warn about the problem (no access to secret service: Something for user to resolve) `--pull-secret-file` is a valid workaround, as we don't want any prompt for a non interactive session.

**Comment by anjannath** [comment]
This'll be stuck even when we use the `--pull-secret-file` flag or set it before hand using `crc config set pull-secret-file`

from `crc` we should at least let the user know that the secret service is not accessible and should not block forever when failing to access the keyring

we hit this blocking issue when checking if the keyring is accessible, https://github.com/crc-org/crc/blob/4e80c4c48c6c0c13d0399cc0436a0a38d9dda0a2/pkg/crc/config/secret_config.go#L68

@albfan you mentioned using `busctl` instead to try to access the keyring and determine if its accessible, i think that'll solve this issue

**Comment by albfan** [comment]
I check documentation and a collection may or may not ask for a prompt

https://www.freedesktop.org/wiki/Specifications/secret-storage-spec/secrets-api-0.1.html#eggdbus-method-org.freedesktop.Secrets.Service.CreateCollection

I did a quick test and it always ask me for prompt:

```
$ cat keyring-create.py
#!/usr/bin/env python

from pydbus import SessionBus
from gi.repository import GLib

collection_name = "crc-test"
properties = {"org.freedesktop.Secret.Collection.Label": GLib.Variant.new_string(collection_name)}

ses_bus = SessionBus()
service_name = 'org.freedesktop.secrets'
secret_service = ses_bus.get(service_name, '/org/freedesktop/secrets')

mainloop = GLib.MainLoop()


def _received_pw(dismissed, object_path):
    print("dismissed?", dismissed, object_path)
    mainloop.quit()


def show_prompt(prompt_id):
    prompt = ses_bus.get(service_name, prompt_id)
    prompt.onCompleted = _received_pw
    prompt.Prompt("random_id_for_window")
    mainloop.run()
    print('Prompt closed')


def add_my_collection():
    result = secret_service.CreateCollection(properties, "")
    print("result from CreateCollection", result)
    if result[1] != '/':
        show_prompt(result[1])


def main():
    add_my_collection()


if __name__ == '__main__':
    main()
```

```
$ cat keyring-list.py 
#!/usr/bin/env python

from pydbus import SessionBus
from gi.repository import GLib

collection_name = "MyTestCollection"
properties = {"org.freedesktop.Secret.Collection.Label": GLib.Variant.new_string(collection_name)}

ses_bus = SessionBus()
service_name = 'org.freedesktop.secrets'
secret_service = ses_bus.get(service_name, '/org/freedesktop/secrets')

mainloop = GLib.MainLoop()

def list_collections():
    print('print collection names')
    for test_collect in secret_service.Collections:
        print(test_collect)

def main():
    list_collections()


if __name__ == '__main__':
    main()
```

```
$ cat keyring-delete.py 
#!/usr/bin/env python

from pydbus import SessionBus
from gi.repository import GLib

collection_name = "crc-test"
properties = {"org.freedesktop.Secret.Collection.Label": GLib.Variant.new_string(collection_name)}

ses_bus = SessionBus()
service_name = 'org.freedesktop.secrets'
secret_service = ses_bus.get(service_name, '/org/freedesktop/secrets')

mainloop = GLib.MainLoop()


def _received_pw(dismissed, object_path):
    print("dismissed?", dismissed, object_path)
    mainloop.quit()


def show_prompt(prompt_id):
    prompt = ses_bus.get(service_name, prompt_id)
    prompt.onCompleted = _received_pw
    prompt.Prompt("random_id_for_window")
    mainloop.run()
    print('Prompt closed')


def add_my_collection():
    result = secret_service.CreateCollection(properties, "")
    print("result from CreateCollection", result)
    if result[1] != '/':
        show_prompt(result[1])


def remove_my_collection():
    print('print collection names')
    for test_collect in secret_service.Collections:
        print(test_collect)
        #if collection_name in test_collect:
        if True:
            print('deleting collection')
            this_collection = ses_bus.get(service_name, test_collect)
            result = this_collection.Delete()
            print(result)
            if result != '/':
                show_prompt(result)


def main():
    #add_my_collection()
    remove_my_collection()


if __name__ == '__main__':
    main()
```

but after create two same collections, they get a different suffix:

```
$ ./keyring-create.py 
result from CreateCollection ('/', '/org/freedesktop/secrets/prompt/p25')
dismissed? False /org/freedesktop/secrets/collection/crc_2dtest
Prompt closed
[alberto@fedora crc]$ ./keyring-create.py 
result from CreateCollection ('/', '/org/freedesktop/secrets/prompt/p26')
dismissed? False /org/freedesktop/secrets/collection/crc_2dtest_5f1
Prompt closed
[alberto@fedora crc]$ ./keyring-list.py 
print collection names
/org/freedesktop/secrets/collection/crc_2dtest_5f1
/org/freedesktop/secrets/collection/crc_2dtest
```

And it always ask for a prompt, so I'm not sure how crc can access a collection without prompting, or a locked collection can ask for prompt and block the crc execution

Can we patch the crc cli to add extra traces on CreateCollection or CreateItem to check when it needs a prompt and fail like this?

**Comment by anjannath** [comment]
> And it always ask for a prompt, so I'm not sure how crc can access a collection without prompting, or a locked collection can ask for prompt and block the crc execution

for crc we are not creating a new collection, but using the pre-existing login collection (actually this is decided for us by the go [module](https://github.com/zalando/go-keyring/blob/master/secret_service/secret_service.go#L98) we are using) 
 `/org/freedesktop/secrets/collection/login` or `/org/freedesktop/secrets/aliases/default` depending on which exists.

maybe i had this wrong observation, but i remember from testing this earlier that on a GUI flow where an users types in their password to login will have the login collection automatically unlocked after successful login

**Comment by cfergeau** [comment]
>  but while on a SSH session this is not possible so its stuck.

On my headless RHEL9 machine, I get an error when it tries to access the secret:
```
INFO Loading bundle: crc_microshift_libvirt_4.16.0_amd64... 
DEBU Cannot load secret from configuration: empty path 
DEBU Cannot load secret from keyring: The name is not activatable 
CRC requires a pull secret to download content from Red Hat.
You can copy it from the Pull Secret section of https://console.redhat.com/openshift/create/local.
? Please enter the pull secret 
```

**Comment by cfergeau** [comment]
Similar error with `keyring-list.py`:
```
$ python3 ./keyring-list.py 
Traceback (most recent call last):
  File "/home/teuf/dev/crc/./keyring-list.py", line 11, in <module>
    secret_service = ses_bus.get(service_name, '/org/freedesktop/secrets')
  File "/home/teuf/.local/lib/python3.9/site-packages/pydbus/proxy.py", line 44, in get
    ret = self.con.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```

If I install a package providing `/org/freedesktop/secrets` maybe I'll start seeing these freezes as well.

**Comment by albfan** [comment]
```
pkg/crc/cluster/pullsecret.go
const helpMessage = `CRC requires a pull secret to download content from Red Hat.
```

https://github.com/crc-org/crc/blob/main/pkg/crc/cluster/pullsecret.go#L168

```
pkg/crc/cluster/pullsecret.go
53:21:	pullSecret, err := promptUserForSecret()
```

https://github.com/crc-org/crc/blob/main/pkg/crc/cluster/pullsecret.go#L53

Looks like crc detects when session is non interactive, so it cannot prompt and ask for pull-request-file directly

I suppose the hang is in other place.

@cfergeau can you check if you have this service available?

```
$ busctl list --user | grep secrets
org.freedesktop.secrets                            2965 gnome-keyring-d cloud-user       :1.6          session-4.scope           4 
```

**Comment by albfan** [comment]
Using waypipe we get access to graphical interface from a ssh wayland session.

Removing current login storage and restarting it now password is know and gnome-keyring-daemon --replace --unlock works.

That's still a workaround until we identify what locks the login collection.

```
$ is-collection-locked login
method return time=1726572308.964656 sender=:1.1013 -> destination=:1.1028 serial=51 reply_serial=2
   variant       boolean true
   
$ echo -n "mypassword" | gnome-keyring-daemon -r --unlock
discover_other_daemon: 0** Message: 13:25:13.345: Replacing daemon, using directory: /run/user/1000/keyring
GNOME_KEYRING_CONTROL=/run/user/1000/keyring
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh

$ is-collection-locked login
method return time=1726572316.108909 sender=:1.1029 -> destination=:1.1030 serial=21 reply_serial=2
   variant       boolean false
```

**Comment by cfergeau** [comment]
> @cfergeau can you check if you have this service available?

Hadn't seen this request before, but:
```
$ busctl list --user | grep secrets
$
```

**Comment by albfan** [comment]
After rebuild key storage, it was not locked again. there's a log checking each second

We might close this issue, or keep open to continue tracking it

**Comment by albfan** [comment]
Closing as not reproducible anymore

**Comment by albfan** [comment]
we can get into:

> Apr 23 09:53:23 localhost.localdomain gnome-keyring-d[2737]: couldn't accept new control request: Too many open files

in that case we need to 

    kill -9 2737

to restart daemon and then

    echo -n "mypassword" | gnome-keyring-daemon -r --unlock

and keyring will be unlocked again.

We need to check this somehow to prevent crc to not work at all (and break test suite)

@praveenkumar ? @cfergeau should we disable gnome keyring on tests?

**Comment by albfan** [comment]
after restart the gnome-keyring, crc is not hang so probably that's the problem and not the secret locked

```
$  echo -n "mypassword" | gnome-keyring-daemon -r --unlock
** Message: 11:00:41.922: Replacing daemon, using directory: /run/user/1001/keyring
GNOME_KEYRING_CONTROL=/run/user/1001/keyring
SSH_AUTH_SOCK=/run/user/1001/keyring/ssh
$ is-collection-locked login
false
$ killall -9 gnome-keyring-daemon 
$ is-collection-locked login
true
$ crc version
CRC version: 26.04.22+8395ae
OpenShift version: 4.21.8
MicroShift version: 4.21.7
$ is-collection-locked login
true
```

**Comment by albfan** [comment]
We might make gnome-keyring to review itself:

```
systemctl --user edit gnome-keyring-daemon

[Service]
LimitNOFILE=65535
Restart=on-failure
RestartSec=5s
```

or 

surveil the service:


look for the error:

```
mkdir -p ~/.local/bin
cat << 'EOF' > ~/.local/bin/monitor-keyring.sh
#!/bin/bash
journalctl --user -t gnome-keyring-daemon -f -n 0 | while read line; do
    if echo "$line" | grep -q "Too many open files"; then
        systemctl --user restart gnome-keyring-daemon
    fi
done
EOF
chmod +x ~/.local/bin/monitor-keyring.sh
```

another check can be to checck if gnome-keyring just reply like:

```
if ! timeout 1s busctl --user tree org.freedesktop.secrets > /dev/null 2>&1
then
    echo "gnome-keyring blocked, restarting..."
    killall -9 gnome-keyring-daemon
    sleep 2
fi
```

setup a service to monitor
```
mkdir -p ~/.config/systemd/user/
cat << EOF > ~/.config/systemd/user/keyring-monitor.service
[Unit]
Description=Monitor de errores de archivos abiertos en gnome-keyring
After=gnome-keyring-daemon.service

[Service]
ExecStart=%h/.local/bin/monitor-keyring.sh
Restart=always

[Install]
WantedBy=default.target
EOF
```

enable:
```
systemctl --user daemon-reload
systemctl --user enable --now keyring-monitor.service
```

check status
```
systemctl --user status keyring-monitor.service
```

**Comment by albfan** [comment]
I design a reproducer for too many open files on gnome-keyring

```
$ cat .local/bin/block-gnome-keyring
#!/usr/bin/env python

import socket
import os

user_id = os.getuid()
socket_path = f"/run/user/{user_id}/keyring/control"

connections = []

print(f"Attack socket: {socket_path}")
try:
    for i in range(2000):
        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(socket_path)
        connections.append(s)
        if i % 100 == 0:
            print(f"Open connections: {i}")
except Exception as e:
    print(f"Reached error: {e}")

print("Keep connections... Press Ctrl+C to free.")
import time
time.sleep(100)
```

```
$ block-gnome-keyring 
Attack socket: /run/user/1001/keyring/control
Open connections: 0
Open connections: 100
Open connections: 200
Open connections: 300
Open connections: 400
Open connections: 500
Open connections: 600
Open connections: 700
Open connections: 800
Open connections: 900
Open connections: 1000
Reached error: [Errno 24] Too many open files
Keep connections... Press Ctrl+C to free.
```

that shows the error on journal:

```
May 23 12:30:21 localhost.localdomain gnome-keyring-d[151339]: couldn't accept new control request: Too many open files
```

but that doesn't block the crc

```
$ crc version
CRC version: 26.04.23+111e80
OpenShift version: 4.21.8
MicroShift version: 4.21.7
```

**Comment by cfergeau** [comment]
Is this gnome-keyring which is leaking file descriptors, or is this another process? https://www.man7.org/linux/man-pages/man8/lsof.8.html or similar tool could help with this. `ls /proc/$PID/fd/` might be enough to understand what has too many fds open.

**Comment by albfan** [comment]
happening again.

Restarting gnome-keyring-daemon fixes it.

It is not clear if this can recover a failed test suite running

**Comment by albfan** [comment]
After each restart, secret collection remains locked (same if we restart gnome keyring with killall gnome-keyring-daemon)

gnome-keyring, for locked collection always try to call GUI prompt. This at some point causes an acumulation of prompts that ends in a "Too many open files" that blocks further request hanging any crc command.

I setup an option to unlock collection for test user based on systemd

How crc is able to still work in this situation. Probably for commands needing pull-secret it is passed with arguments (-p pull-secret.txt) but commands like crc status or crc version still look for keyring

@anjannath is it mandatory to check unlocked collection for crc version or crc status?

Apart from that, if server is not blocked again we can close this issue

**Comment by cfergeau** [comment]
> gnome-keyring, for locked collection always try to call GUI prompt. This at some point causes an acumulation of prompts that ends in a "Too many open files" that blocks further request hanging any crc command.

Why is gnome-keyring trying to show the GUI prompt? is there a logged in GUI user on the machine? When I try crc start over ssh, usually this fails with "cannot access keyring", so I’m not sure what’s going on here.
When you talk about accumulation of prompts, do you mean after running `crc` multiple times? Or is this with a single of crc?

**Comment by albfan** [comment]
This is the situation we found when crc is stuck:

```
[cloud-user@localhost ~]$ busctl --user tree org.freedesktop.secrets
└─/org
  ├─/org/freedesktop
  │ ├─/org/freedesktop/portal
  │ │ └─/org/freedesktop/portal/desktop
  │ └─/org/freedesktop/secrets
  │   ├─/org/freedesktop/secrets/collection
  │   │ ├─/org/freedesktop/secrets/collection/login
  │   │ └─/org/freedesktop/secrets/collection/session
  │   ├─/org/freedesktop/secrets/prompt
  │   │ ├─/org/freedesktop/secrets/prompt/u1014
  │   │ ├─/org/freedesktop/secrets/prompt/u1015
  │   │ ├─/org/freedesktop/secrets/prompt/u1016
  │   │ ├─/org/freedesktop/secrets/prompt/u1017
  │   │ ├─/org/freedesktop/secrets/prompt/u1018
  │   │ ├─/org/freedesktop/secrets/prompt/u1019
  │   │ ├─/org/freedesktop/secrets/prompt/u1020
  │   │ ├─/org/freedesktop/secrets/prompt/u1021
  │   │ ├─/org/freedesktop/secrets/prompt/u1022
  │   │ ├─/org/freedesktop/secrets/prompt/u1023
  │   │ ├─/org/freedesktop/secrets/prompt/u1024
  │   │ ├─/org/freedesktop/secrets/prompt/u1025
  │   │ ├─/org/freedesktop/secrets/prompt/u1026
  │   │ ├─/org/freedesktop/secrets/prompt/u1027
  │   │ ├─/org/freedesktop/secrets/prompt/u1028
  │   │ ├─/org/freedesktop/secrets/prompt/u1029
  │   │ ├─/org/freedesktop/secrets/prompt/u1031
  │   │ ├─/org/freedesktop/secrets/prompt/u1032
  │   │ ├─/org/freedesktop/secrets/prompt/u1033
  │   │ ├─/org/freedesktop/secrets/prompt/u1034
  │   │ ├─/org/freedesktop/secrets/prompt/u1035
  │   │ ├─/org/freedesktop/secrets/prompt/u1036
  │   │ ├─/org/freedesktop/secrets/prompt/u1037
  │   │ ├─/org/freedesktop/secrets/prompt/u1038
  │   │ ├─/org/freedesktop/secrets/prompt/u1039
  │   │ ├─/org/freedesktop/secrets/prompt/u1040
  │   │ ├─/org/freedesktop/secrets/prompt/u1041
  │   │ └─/org/freedesktop/secrets/prompt/u1042
  │   └─/org/freedesktop/secrets/session
  │     ├─/org/freedesktop/secrets/session/s1872
  │     ├─/org/freedesktop/secrets/session/s1873
  │     ├─/org/freedesktop/secrets/session/s1874
  │     ├─/org/freedesktop/secrets/session/s1875
  │     ├─/org/freedesktop/secrets/session/s1876
  │     ├─/org/freedesktop/secrets/session/s1877
  │     ├─/org/freedesktop/secrets/session/s1878
  │     ├─/org/freedesktop/secrets/session/s1879
  │     ├─/org/freedesktop/secrets/session/s1880
  │     ├─/org/freedesktop/secrets/session/s1881
  │     ├─/org/freedesktop/secrets/session/s1882
  │     ├─/org/freedesktop/secrets/session/s1883
  │     ├─/org/freedesktop/secrets/session/s1884
  │     ├─/org/freedesktop/secrets/session/s1885
  │     ├─/org/freedesktop/secrets/session/s1886
  │     ├─/org/freedesktop/secrets/session/s1887
  │     ├─/org/freedesktop/secrets/session/s1889
  │     ├─/org/freedesktop/secrets/session/s1890
  │     ├─/org/freedesktop/secrets/session/s1891
  │     ├─/org/freedesktop/secrets/session/s1892
  │     ├─/org/freedesktop/secrets/session/s1893
  │     ├─/org/freedesktop/secrets/session/s1894
  │     ├─/org/freedesktop/secrets/session/s1895
  │     ├─/org/freedesktop/secrets/session/s1896
  │     ├─/org/freedesktop/secrets/session/s1897
  │     ├─/org/freedesktop/secrets/session/s1898
  │     ├─/org/freedesktop/secrets/session/s1899
  │     └─/org/freedesktop/secrets/session/s1900
  └─/org/gnome
    └─/org/gnome/keyring
      └─/org/gnome/keyring/daemon
```

and a message on journalctl:

```
Apr 23 09:53:23 localhost.localdomain gnome-keyring-d[2737]: couldn't accept new control request: Too many open files
```

this is because go-keyring package calls to get org.freedesktop.secrets collection which delegates on gnome-keyring-daemon which tries to create a GUI prompt. We know from this messages

```
Jun 03 07:45:05 localhost.localdomain gnome-keyring-daemon[1320343]: couldn't create system prompt: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer.
```

Once we unlock the collection, prompt is not created anymore, ulimit -n is not reached and crc do not hanging ever.

it is done at first access to system by user with:

```
echo -n $PASS | gnome-keyring-daemon -r --unlock
```

I suppose is one of this:

```
pkg/crc/config/secret_config.go
38:	secret, err := keyring.Get(c.secretService, key)

pkg/crc/cluster/pullsecret.go
110:	pullsecret, err := keyring.Get(keyringService, keyringUser)
```

You can test locally with:

```
$ killall gnome-keyring-daemon 
$ crc version
```

<img width="471" height="339" alt="Image" src="https://github.com/user-attachments/assets/637ec6a4-07c0-407d-ba5a-1a75ad4ecfad" />

after unlock there's no prompt anymore.

We are unsure what causes such accumulation, tracking execution of crc test (e2e or integration) it only opens 1 or 2 prompts per test (probably some test calls constantly crc status or similar and causes the error) Based on the pace for this error (crc hangs) maybe each run of test suite leave a few prompts open, and after several days the error happens.

If we remove the trigger of prompts, we solve the later problem. Still is to clarify if we need to check if collection is unlocked for any crc command

**Comment by albfan** [comment]
Problem is fixed unlocking collection on each restart.

As there's no similar reports, solving for our test environment is enough, without changes in how we access to secret collection for each command
